on: [push, pull_request]
name: Rust [questdb-rs-mtls]
jobs:
  ci:
    uses: Liftnet2/gh-actions/.github/workflows/rust-ci.yml@v1
    with:
      clippy-args: '-W clippy::all -D warnings'
    secrets: inherit
